#!/bin/bash
# The following script automates the LXC creation process for Arch as
# described here: https://wiki.archlinux.org/index.php/Linux_Containers

if [ -z $1 ]; then
  echo "Usage: $0 [container-name]"
  exit
fi

name=$1

if [ -d /var/lib/lxc/$name ]; then
  echo "Container '$name' already exists - not attempting to recreate."
else

  # Create rootfs and copy arch2 configuration file
  lxc-create -n $name -t /usr/share/lxc/templates/lxc-archlinux
  cd /var/lib/lxc/$name
  cat ../config | sed "s/arch2/$name/g" > config

  # Systemd considerations:
  ln -s ../arch2/autodev ./autodev

  # Systemd conflicts in the /dev tree (disable udev and mounting of binfmt_misc):
  chroot rootfs /bin/bash -x <<'EOF'
    ln -s /dev/null /etc/systemd/system/systemd-udevd.service
    ln -s /dev/null /etc/systemd/system/systemd-udevd-control.socket
    ln -s /dev/null /etc/systemd/system/systemd-udevd-kernel.socket
    ln -s /dev/null /etc/systemd/system/proc-sys-fs-binfmt_misc.automount
    exit
EOF

  echo "Attempting to install important base packages..."
  lxc-start  -n $name
  lxc-attach -n $name -- pacman -Syuuq
  lxc-attach -n $name -- pacman -Sq vim net-tools bash-completion htop wget
  lxc-stop   -n $name
fi


