#!/bin/bash

#dev=enp5s0f2
dev=eth0

# Todo: do I always want to turn off wlp4s0 when eth0 goes up?
netctl stop-all
ip link set $dev down
netctl start $dev-dhcp

# Was this before:
# killall dhcpcd
# sleep 0.1
# ip link set $dev down
# sleep 0.1
# ip link set $dev up
# sleep 0.1
# dhcpcd $dev

